# -*- coding: utf-8 -*-
"""Jesse finale Copy of  Paper Scissors project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3C5wjZ0hQ40N0TVcdNNslBBIE8LvHTC

# Rock Paper Scissors Hackathon Project
The familiar game of Rock, Paper, Scissors is played like this: at the same time, two players display one of three symbols: a rock, paper, or scissors. 
- A rock beats scissors.
- Scissors beat paper by cutting it 
- Paper beats rock by covering it.

In our game, we will have the user input one of the three symbols and then the computer will randomly choose one too. We will continue to play until the user wants to quit.

Bellow is what the output and input of the program will look like:
"""

# Add the code needed to this function.
def getUserInput():
 aW = ("rock", "paper", "scissors", "quit" )
 while True:
    usr_choice =input("rock, paper, or scissors , or quit: ")
    if usr_choice in aW:
      return usr_choice
    else:
      print("Invalid response,try again !")

# Add the code needed to this function
def compare_hands(player_input,computer_choice):
  if player_input == "rock":
    if computer_choice == "rock":
      print("There is a tie.")
      return("tie")
    elif computer_choice == "paper":
      print("Paper covers rock, you lose.")
      return("loss")
    elif computer_choice == "scissors":
      print("Rock crushes scissors, you win.")
      return("win")
  elif player_input == "paper":
    if computer_choice == "paper":
      print("There is a tie.")
      return("tie")
    elif computer_choice == "scissors":
      print("Scissors cuts paper, you lose.")
      return("loss")
    elif computer_choice == "rock":
      print("paper covers rock, you win.")
      return("win")
  elif player_input == "scissors":
    if computer_choice == "scissors":
      print("There is a tie.")
      return("tie")
    elif computer_choice == "rock":
      print("Rock smashes scissors, you lose.")
      return("loss")
    elif computer_choice == "paper":
      print("Scissors cuts paper, you win.")
      return("win")
  
  # function will play 1 "round" of rock paper scissors against the player
  # it will then return "tie","win" or "loss" based on how the user does

"""You can use the code block bellow to check that your code works. Run the cell and follow the directions in blue. This will tell you if you have any errors or if the code is correct and you can move on."""

# here is an example on how to convert a decimal into a percentage

# take two numbers
num1 = 1
num2 = 3

# save the percent up to 5 decimal places
percent = "{:.5%}".format(num1/num2)
print(percent)

# save the percent up to 1 decimal places
percent = "{:.1%}".format(num1/num2)
print(percent)

# now figure out how to save the precent up to 2 decimal places...

def endGameDisplay(player_wins, games_played):
  # this function will display 
  games_played = 0
  player_wins = 0

  percent = "{:.2%}".format(player_wins/games_played)
  print("You have won"  +  percent  +  "of games")

"""# Part 5: Now Everything Together 
You have finished writing all the functions! Now run the main code and make sure everything works well when combined together!
"""

from random import choice

# set up variables we need
games_played = 0
player_wins = 0 
computer_wins = 0
player_input = ""

# while the player does not input quit
while player_input != "quit":

  # get the user input from the player
  player_input = getUserInput()

  # if they did not input quit
  if player_input != "quit":
 
    # have the computer choose either rock, paper or scissors randomly
    computer_choice = choice(["rock","paper","scissors"])

    # compare the the choice of the computer and the player 
    # then save if the player  has a "win" or "loss"
    win_status = compare_hands(player_input,computer_choice)
    
    # if the player won increase their score
    if win_status == "win":
      player_wins +=1
    
    # if the player lost then increase the computer score
    if win_status == "loss":
      computer_wins += 1
    
    # if it is a tie we dont need to increase either of their score

    # we finished a round 
    games_played += 1 

    # print out the current score of the player and computer
    print(f"Player: {player_wins}  vs Computer: {computer_wins}")
    print()


# once we are outside of the while loop it meant that the player has
# decided to quit so we should display percent of games the player won
endGameDisplay(player_wins, games_played)

