# -*- coding: utf-8 -*-
"""Word Guesser

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zatlClHbog0PRlIs4k6iVmLz95dR7LXa
"""

def displaySecretWord(word, guesses):
 
  # Go through each letter in the secret word, and determine HOW we display it
  for letter in word:
 
    # If this letter (from the secret word) has been guessed, display the letter
    if(letter in guesses):
      print(letter, end=" ")
    # Otherwise, display an underscore ( _ )
    else:
      print("_", end="")

def hasUserWon(word, guesses):
 
  # Let's use an "Innocent Until Proven Guilty" Algorithm...
  # ...and create a variable that is set to "True"
  won = True
 
  # Go through each letter in the secret word
  for letter in word:
 
    # Check if the letter has been guessed
    if(letter not in guesses):
 
      # If it has NOT been guessed, set the variable we created to False, and stop the loop
      won = False
      break
 
  return won

def getGuess():

      guess = input('Guess a letter: ')
      guess = guess.lower()
      return guess

def displayBoard(secrectWord, alreadyGuessed):
    for letter in secretWord: 
      if (letter in alreadyGuessed ) :
        print(letter ,end="")
      else:
        print("_", end="")
    print("\n")

def isWordGuessed(secretWord, alreadyGuessed):
    for i in secretWord:
      if i not in alreadyGuessed:
        return False
    return True




secretWord = 'spiderman'
alreadyGuessed= ''
strikes = 0

while True:

  guess = getGuess()
  if(guess in secretWord):

    alreadyGuessed = alreadyGuessed + guess
    print('Good Guess!')
    displayBoard(secretWord, alreadyGuessed)
  elif guess in alreadyGuessed:
    print('You have already guessed that letter. Choose again.')
  elif guess not in 'abcdefghijklmnopqrstuvwxyz':
    print('Please enter a single letter. ')
  else:
    alreadyGuessed = alreadyGuessed + guess
    print(guess.upper() + ' is not in the word') 
    strikes = strikes + 1
    if strikes == 1:
      print("you have 1 stike. If you get 5, you lose.")
    elif strikes == 5:
      print('You lost. The word was'  +  secretWord + '.')
      break
    else:
      print("You have" +  str(strikes) + " strikes. If you get " + str(5  - strikes) + " more you lose.")
  if isWordGuessed(secretWord, alreadyGuessed):
    print("You've guessed the secret word. You WIN !!")
    break

